apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-readiness
  labels:
    app: go-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-demo-app-readiness
  template:
    metadata:
      labels:
        app: go-demo-app-readiness
    spec:
      containers:
      - name: web
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /readyz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
# Traffic is only routed to the Pod after the readiness probe succeeds.
