apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-multicontainer
  labels:
    app: go-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-demo-app-mc
  template:
    metadata:
      labels:
        app: go-demo-app-mc
    spec:
      volumes:
      - name: applogs
        emptyDir: {}
      containers:
      - name: web
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
        env:
        - name: NGINX_ACCESS_LOG
          value: "/var/log/app/access.log"
        volumeMounts:
        - name: applogs
          mountPath: /var/log/app
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
      - name: log-sidecar
        image: busybox:1.36
        command: ["sh","-c","touch /var/log/app/access.log; tail -F /var/log/app/access.log"]
        volumeMounts:
        - name: applogs
          mountPath: /var/log/app
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
# Sidecar tails the shared volume to stream access logs.
