apiVersion: batch/v1
kind: Job
metadata:
  name: one-off-migration
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: runner
        image: busybox:1.36
        command: ["sh","-c","echo data migration complete"]
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
