apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox:1.36
              command: ["echo", "Hello world"]
          restartPolicy: OnFailure
