apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-liveness
  labels:
    app: go-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-demo-app-liveness
  template:
    metadata:
      labels:
        app: go-demo-app-liveness
    spec:
      containers:
      - name: web
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 3
# If liveness check fails 3 times consecutively, kubelet restarts the container.
